INFO: Running heudiconv version 0.11.3+d20220512 latest 0.11.4
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 'voice981', 'outdir': '/out/', 'session': '1'}
INFO: Processing 5274 dicoms
INFO: Reloading existing filegroup.json because /out/.heudiconv/voice981/ses-1/info/voice981_ses-1.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Converting /out/sub-voice981/ses-1/anat/sub-voice981_ses-1_T2w (176 DICOMs) -> /out/sub-voice981/ses-1/anat . Converter: dcm2niix . Output types: ('nii.gz',)
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/src/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/src/heudiconv/heudiconv/main.py", line 393, in workflow
    grouping=grouping,)
  File "/src/heudiconv/heudiconv/convert.py", line 217, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 553, in convert
    % (outname)
RuntimeError: was asked to convert into /out/sub-voice981/ses-1/anat/sub-voice981_ses-1_T2w.nii.gz but destination already exists
